[package]
name = "libproper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { version = "0.31.0", features = ["bytemuck"] }
vulkano = { version = "0.29.0", features = ["nalgebra"] }
vulkano-shaders = "0.29.0"
vulkano-win = "0.29.0"
winit = "0.26.1"
